version: '3.8'
services:
  db:
    image: postgres:14
    container_name: nest-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nest-network

  nest-app:
    container_name: nest-app
    build: .
    ports:
      - '${NEST_PORT}:3000'
    depends_on:
      - db
    networks:
      - nest-network

volumes:
  db-data:

networks:
  nest-network:
