version: '3'
services:
  db:
    env_file:
      - ../config/.env.development
    image: postgres:14
    container_name: coura-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nest-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    # 필요하면 volume, 환경 변수, 비밀번호 설정 등 추가 가능
    # environment:
    #   REDIS_PASSWORD: example
    # command: ["redis-server", "--requirepass", "example"]
    networks:
      - nest-network

  nest-app:
    container_name: nest-app
    # build: .
    build:
      context: ../ # 프로젝트 루트가 빌드 컨텍스트
      dockerfile: docker/Dockerfile.dev # 빌드 컨텍스트(프로젝트 루트) 내에서 Dockerfile의 경로 지정
    env_file:
      - ../config/.env.development
    ports:
      - '${NEST_PORT}:3000'
        # - '11582:3000'
        # - '80:3000'
        # - '443:3000'
    expose:
      - 3000
    depends_on:
      - db
    networks:
      - nest-network
    restart: always

volumes:
  db-data:

networks:
  nest-network:
